services:
  swiftline.api:
    image: ${DOCKER_REGISTRY-}swiftlineapi
    container_name: swiftline.api
    build:
      context: .
      dockerfile: SwiftLine.API/Dockerfile
    ports:
       - "5000:5000"
       - "5001:5001"
  swiftline.database:
    image: postgres:latest
    container_name: swiftline.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiftline
    volumes:
        - ./.containers/switfline-db:/var/lib/postgresql/data
    ports:
        - "5432:5432"    