// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Infrastructure
{
    public partial class WaitTimeEstimator
    {
        /// <summary>
        /// model input class for WaitTimeEstimator.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"EventId")]
            public float EventId { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"TimeWaited")]
            public float TimeWaited { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"AvgServiceTimeWhenJoined")]
            public float AvgServiceTimeWhenJoined { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"DayOfWeek")]
            public string DayOfWeek { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"NumActiveServersWhenJoined")]
            public float NumActiveServersWhenJoined { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"PositionInQueueWhenJoined")]
            public float PositionInQueueWhenJoined { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"TimeOfDay")]
            public string TimeOfDay { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"TotalPeopleInQueueWhenJoined")]
            public float TotalPeopleInQueueWhenJoined { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for WaitTimeEstimator.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"EventId")]
            public float EventId { get; set; }

            [ColumnName(@"TimeWaited")]
            public float TimeWaited { get; set; }

            [ColumnName(@"AvgServiceTimeWhenJoined")]
            public float AvgServiceTimeWhenJoined { get; set; }

            [ColumnName(@"DayOfWeek")]
            public float[] DayOfWeek { get; set; }

            [ColumnName(@"NumActiveServersWhenJoined")]
            public float NumActiveServersWhenJoined { get; set; }

            [ColumnName(@"PositionInQueueWhenJoined")]
            public float PositionInQueueWhenJoined { get; set; }

            [ColumnName(@"TimeOfDay")]
            public float[] TimeOfDay { get; set; }

            [ColumnName(@"TotalPeopleInQueueWhenJoined")]
            public float TotalPeopleInQueueWhenJoined { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = "C:\\Users\\ekpok\\source\\repos\\SwitfLine\\Infrastructure\\WaitTimeEstimator.mlnet";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
