// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Extensions.Hosting;
namespace Infrastructure
{
    public partial class WaitTimeEstimator
    {
       
        /// <summary>
        /// model input class for WaitTimeEstimator.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"AvgServiceTimeWhenJoined")]
            public float AvgServiceTimeWhenJoined { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"NumActiveServersWhenJoined")]
            public float NumActiveServersWhenJoined { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"EffectiveQueuePosition")]
            public float EffectiveQueuePosition { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Batches")]
            public float Batches { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"TimeWaited")]
            public float TimeWaited { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for WaitTimeEstimator.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"AvgServiceTimeWhenJoined")]
            public float AvgServiceTimeWhenJoined { get; set; }

            [ColumnName(@"NumActiveServersWhenJoined")]
            public float NumActiveServersWhenJoined { get; set; }

            [ColumnName(@"EffectiveQueuePosition")]
            public float EffectiveQueuePosition { get; set; }

            [ColumnName(@"Batches")]
            public float Batches { get; set; }

            [ColumnName(@"TimeWaited")]
            public float TimeWaited { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

      
        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            var MLNetModelPath = Path.Combine(AppContext.BaseDirectory, "WaitTimeEstimator.mlnet");
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
